In [77]:
# Import packages
%matplotlib inline
import numpy as np
import scipy as sp
import scipy.stats as sps
import matplotlib.pyplot as plt
import pandas as  pd
import math as mt
import seaborn as sns

In [135]:
data_path='/Users/yangyingkang/Downloads/chrome下载/Data Interdisciplinary Project.xlsx'
DF=pd.read_excel(data_path)
DF

From                                2001-01-31 00:00:00  \
0     To                                2021-04-30 00:00:00   
1    NaN  Monthly returns (net of taxes and investment f...   
2    NaN                                               DATE   
3      4                                2001-01-31 00:00:00   
4      5                                2001-02-28 00:00:00   
..   ...                                                ...   
242  243                                2020-12-31 00:00:00   
243  244                                2021-01-31 00:00:00   
244  245                                2021-02-28 00:00:00   
245  246                                2021-03-31 00:00:00   
246  247                                2021-04-30 00:00:00   

                           1              Unnamed: 3  \
0                        244                     NaN   
1                        NaN                     NaN   
2    Australian Equities (G)  Developed Equities (G)   
3                  0.0431977               0.0260299   
4                -0.00187427              -0.0786783   
..                       ...                     ...   
242                0.0131964               0.0350668   
243               0.00331737             -0.00772246   
244                0.0147604               0.0264729   
245                0.0229637               0.0420913   
246                 0.036974               0.0404377   

                       Unnamed: 4                     Unnamed: 5  \
0                             NaN                            NaN   
1                             NaN                            NaN   
2    Emerging Market Equities (G)  Australian Fixed Interest (D)   
3                         0.13824                      0.0150034   
4                      -0.0678592                     0.00667544   
..                            ...                            ...   
242                     0.0606605                    -0.00272124   
243                     0.0380541                    -0.00419282   
244                     0.0103307                     -0.0358089   
245                   -0.00871113                     0.00800359   
246                     0.0160339                     0.00562161   

                      Unnamed: 6   Unnamed: 7  
0                            NaN          NaN  
1                            NaN          NaN  
2    Global Government Bonds (D)     Cash (D)  
3                       0.010966   0.00536417  
4                      0.0102496   0.00469495  
..                           ...          ...  
242                   0.00179122  2.56511e-05  
243                  -0.00652406  1.23602e-05  
244                   -0.0185919 -4.55976e-06  
245                  -0.00210882  2.02679e-05  
246                  0.000422977  2.88946e-05  

[247 rows x 8 columns]

In [166]:
#df = pd.DataFrame(DF, columns= ['DATE','Cash(D)'])
DF=pd.DataFrame(DF)

In [167]:
#df = df.iloc[: , :]
DF1=DF.iloc[75:123 ,2 :8]###75,123       ##123 171
#

In [177]:
###q5(b)###   change  75,122  into     ##123 171 to compute period B
e=np.ones(6)
es=[[1],[1],[1],[1],[1],[1]]
C=DF1.astype(float).cov().values*24
m=DF1.mean(axis=0).values*24
ms=([[ 0.02769809], [-0.02423538],  [0.20039497],  [0.12586716],  [0.15730639],[0.10934711]])
ecm=e@C**(-1)@ms
mcm=m@C**(-1)@ms
ece=e@C**(-1)@es
mce=m@C**(-1)@es
left=(1*mcm-0.12*ecm)
righ=ece*0.12-mce
bot=ece*mcm-ecm*mce
w=(left*C**(-1)@e+righ*(C**(-1))@m)/bot
w

array([-0.01330743, -0.01169857, -0.00881197,  0.05988096,  0.16298624,
        0.81095068])

In [178]:
####array([-0.01330743, -0.01169857, -0.00881197,  0.05988096,  0.16298624,0.81095068])
sum([-0.01330743, -0.01169857, -0.00881197,  0.05988096,  0.16298624,
        0.81095068])

0.9999999100000001

In [179]:
DF1=DF.iloc[123:171 ,2 :8]
e=np.ones(6)
es=[[1],[1],[1],[1],[1],[1]]
C=DF1.astype(float).cov().values*24
m=DF1.mean(axis=0).values*24
ms=([[0.1610965] , [0.23049693], [0.06629901], [0.14873265], [0.15720843],
       [0.07137963]])
ecm=e@C**(-1)@ms
mcm=m@C**(-1)@ms
ece=e@C**(-1)@es
mce=m@C**(-1)@es
left=(1*mcm-0.12*ecm)
righ=ece*0.12-mce
bot=ece*mcm-ecm*mce
w=(left*C**(-1)@e+righ*(C**(-1))@m)/bot
w

array([-0.10328555, -0.0935013 , -0.15134977,  0.30340986,  0.56537992,
        0.47934683])

In [180]:
####(B)array([-0.10328555, -0.0935013 , -0.15134977,  0.30340986,  0.56537992, 0.47934683])
sum(([-0.10328555, -0.0935013 , -0.15134977,  0.30340986,  0.56537992, 0.47934683]))

0.99999999

In [181]:
DF15=DF.iloc[170:195 ,2 :8]

In [182]:
DF15

1  Unnamed: 3   Unnamed: 4   Unnamed: 5   Unnamed: 6  \
170    0.0204025 -0.00777184   -0.0248661    0.0168514    0.0105416   
171    0.0322359 -0.00546895    0.0142047    0.0161036    0.0231298   
172    0.0692223    0.058939     0.032858   0.00279818  -0.00635974   
173 -0.000517375 -0.00430833   0.00142255   0.00759704   0.00972306   
174   -0.0164749   0.0104131    0.0567798   -0.0110799  -0.00509663   
175   0.00428715   0.0126768   -0.0251367  0.000361744  -0.00401751   
176   -0.0531526  -0.0294153   -0.0225689   -0.0092567   -0.0104077   
177    0.0431341   0.0249389   -0.0435735    0.0130001    0.0141134   
178   -0.0769773  -0.0665381   -0.0649012    0.0063708 -0.000265445   
179   -0.0285788  -0.0354937   -0.0171106   0.00250023     0.010317   
180    0.0442047   0.0787407     0.054245   0.00299177   0.00425555   
181  -0.00681656  0.00640671   -0.0268756  -0.00875928   0.00202398   
182    0.0272807  -0.0215746   -0.0107093   0.00332833  0.000123963   
183   -0.0544973  -0.0541461   -0.0522358    0.0122221    0.0214953   
184   -0.0172471  -0.0153358  0.000646809    0.0103434    0.0140495   
185    0.0477615   0.0526547    0.0832716  -0.00213189   0.00653791   
186    0.0333976  0.00858848 -0.000774293   0.00258719  0.000461903   
187    0.0313632   0.0176121  -0.00805699    0.0125605   0.00713392   
188   -0.0244223  -0.0131584    0.0159271    0.0132685    0.0234406   
189    0.0635923   0.0411975    0.0423669   0.00735379   0.00403248   
190   -0.0155685  0.00420726    0.0275944   0.00421832  -0.00222552   
191   0.00514342  0.00194928   0.00442581  -0.00224814  0.000490869   
192   -0.0217479  -0.0066916   0.00613517   -0.0127639   -0.0116265   
193    0.0280495   0.0263408   -0.0217929   -0.0143994    -0.015232   
194    0.0434044   0.0277608   0.00139684  -0.00171563   0.00282013   

     Unnamed: 7  
170  0.00231812  
171  0.00251427  
172  0.00208973  
173  0.00205287  
174  0.00179722  
175  0.00200263  
176  0.00175895  
177  0.00180362  
178  0.00180944  
179  0.00176185  
180  0.00189108  
181  0.00166704  
182   0.0019155  
183  0.00201006  
184  0.00177883  
185  0.00198064  
186  0.00198949  
187  0.00193511  
188  0.00164841  
189  0.00173015  
190  0.00168927  
191  0.00141593  
192   0.0014612  
193  0.00144548  
194  0.00145132

In [183]:
X=np.log((DF15+1).astype(float).values)####q5(d)
realq5=np.exp(sum(X))-1
realq5

array([0.17273021, 0.10397391, 0.0080793 , 0.07359762, 0.10295507,
       0.04694382])

In [184]:
m@realq5.T ##realised return for 5(d)

0.0828101571149292